version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    reviewers:
      - "jcasner"
    groups:
      react:
        patterns:
        - "*react*"
        - "@react*"
      vite:
        patterns:
        - "vite*"
        - "@vite*"
